### ISSUE TITLE
Invalid configuration object. when Installing

### ISSUE THREAD

**Issue by susmita-k** [Gethyl/AngularJsWithReact#2]
Hi Gethyl,

I am trying to install - AngularJsWithReact , as per your instruction, but ran into this error with - npm start  : 

`

✖ ｢wds｣: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module has an unknown property 'loaders'. These properties are valid:
   object { defaultRules?, exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, noParse?, rules?, strictExportPresence?, strictThisContextOnImports?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, unsafeCache?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp? }
   -> Options affecting the normal modules (`NormalModuleFactory`).

`

**Comment by susmita-k** [comment]
Hi Gethyl,

So we got past the above error and now getting the new error - 
`ERROR in ./main.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: Cannot read property 'babel' of undefined
    at Object.module.exports (/home/wolkvolk/Install/Test/AngularJsWithReact/node_modules/babel-loader/lib/index.js:103:36)
 @ multi ./main.js ./src/angular/reactDirective.js bundle[0]

ERROR in ./src/angular/reactDirective.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: Cannot read property 'babel' of undefined
    at Object.module.exports (/home/wolkvolk/Install/Test/AngularJsWithReact/node_modules/babel-loader/lib/index.js:103:36)
 @ multi ./main.js ./src/angular/reactDirective.js bundle[1]`
